# Generated by Django 5.2.7 on 2025-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EEGRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data_s3", models.URLField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("mood_inference", models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
